#!/usr/bin/env python
from sys import exit
from sys import argv
from getopt import getopt, GetoptError

ACTIONS = { 
            0 : "GUI mode",
            1 : "Update templates",
            2 : "List templates"
          }

def _help():
    print """
NAME
    opennode: OpenNode Terminal User Interface (TUI)

SYNOPSIS
    opennode [OPTIONS]

OPTIONS
    -u, --update-templates
        Update locally stored remote templates
    -l, --list-templates
        List local and remote templates in all storage pools
    -h, --help
        Display usage help

SEE ALSO:
    OpenNode web page:
    http://opennodecloud.com
    """
    exit(2)

if __name__ == '__main__':
    #Run OpenNode utility

    try:
        options, args = getopt(argv[1:], 'ulh', ['update-templates','list-templates','help'])
    except GetoptError, err:
        # print help information and exit:
        print str(err) # will print something like "option -a not recognized"
        _help()
        exit(2)

    action = 'cli'

    for o, a in options:
        if o in ("-u", "--update-templates"): action = 'lib_update'
        elif o in ("-l", "--list-templates"): action = 'lib_list'
        elif o in ("-h", "--help"): _help()
    
    if action == 'cli':
        from opennode.cli import screen 
        tui = screen.OpenNodeTUI()
        tui.run()
    elif action == 'lib_list':
        from opennode.cli.actions import templates
        templates.list_templates()
