#!/usr/bin/python
###########################################################################
#
#    Copyright (C) 2009-2011 Active Systems LLC, 
#    url: http://www.active.ee, email: info@active.ee
#
#    This file is part of OpenNode.
#
#    OpenNode is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    OpenNode is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with OpenNode.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

import os
import sys
from sys import exit, argv
from getopt import getopt
from decimal import *

from opennode.cli.actions.vm import openvz
from opennode.cli.config2 import openvz_config

def _help():
    print """
NAME
    vzcfgcreator: OpenVZ CT UBC configuration generator utility.

SYNOPSIS
    vzcfgcreator [OPTIONS] 

OPTIONS:
    -m, --memory=X
        Guaranteed memory (in GB) for container
        Default: 0.25GB
    -s, --swap=X
        Swap space (in GB) for container
        Default: 0.25GB
    -d, --disk=X
        Disk space allocation limit for container (in GB)
        Default: 10GB
    -c, --cpus=X
        Number of CPUs enabled for container
        Default: 1
    -l, --limitcpu=X
        CPU usage limit (in %)
        Default: 50%
    -h, --help
        Display usage help.

AUTHOR:
    Andres Toomsalu (andres@active.ee)
    Active Systems LLC 

SEE ALSO:
    OpenNode web page:
    http://opennode.activesys.org
    """
    exit()

if __name__ == '__main__':
    #sys.stdout.write(os.popen('clear').read())
    try:
        options, args = getopt(argv[1:], 'm:s:d:c:l:h', 
                               ['memory=', 'swap=', 'disk=', 'cpus=', 
                               'limitcpu=', 'help'])
    except getopt.GetoptError, err:
        # print help information and exit:
        _help()
        print str(err) # will print something like "option -a not recognized"
        exit(2)
    
    memory = swap = disk = cpus = cpulimit = ''
    
    for o, a in options:
        if o in ("-m", "--memory"): memory = a
        elif o in ("-s", "--swap"): swap = a
        elif o in ("-d", "--disk"): disk = a
        elif o in ("-c", "--cpus"): cpus = a
        elif o in ("-l", "--limitcpu"): cpulimit = a
        elif o in ("-h", "--help"): _help()
        else: assert False, "unhandled option"
    
    #print inputvars
    inputvars = {
        "memory": memory or openvz_config.c("ovf-defaults", "memory"),
        "swap": swap or openvz_config.c("ovf-defaults", "swap"),
        "disk": disk or openvz_config.c("ovf-defaults", "disk"),
        "vcpu": cpus or openvz_config.c("ovf-defaults", "vcpu"),
        "vcpulimit": cpulimit or openvz_config.c("ovf-defaults", "vcpulimit")
    }
    vzconf = openvz.generate_ubc_config(inputvars)
    print vzconf
