''' Containes templates for openvz and kvm configuraion files'''

openvz_template = """\
#+--------------------------------------------------------------+
#| CT configuration generated by OpenNode-tui openvz script \t|
#+--------------------------------------------------------------+
#| Input params were \t\t\t\t\t\t|
#+--------------------------------------------------------------+
#| MEMORY    : %(physpages_barrier)sG \t\t\t\t\t\t|
#| SWAPPAGES : %(swappages_barrier)sG \t\t\t\t\t\t|
#| DISK      : %(diskspace_soft)sG \t\t\t\t\t\t|
#| CPUS      : %(cpus)s \t\t\t\t\t\t|
#| CPULIMIT  : %(cpulimit)s%% \t\t\t\t\t\t|
#+--------------------------------------------------------------+      
#| Generated : %(time)s \t\t\t|
#+--------------------------------------------------------------+


# UBC parameters (in form of barrier:limit)
PHYSPAGES="%(physpages_barrier)sG:%(physpages_limit)sG"
SWAPPAGES="%(swappages_barrier)sG:%(swappages_limit)sG"
KMEMSIZE="unlimited"
LOCKEDPAGES="unlimited"
PRIVVMPAGES="unlimited"
SHMPAGES="unlimited"
NUMPROC="unlimited"
VMGUARPAGES="unlimited"
OOMGUARPAGES="unlimited"
NUMTCPSOCK="unlimited"
NUMFLOCK="unlimited"
NUMPTY="unlimited"
NUMSIGINFO="unlimited"
TCPSNDBUF="unlimited"
TCPRCVBUF="unlimited"
OTHERSOCKBUF="unlimited"
DGRAMRCVBUF="unlimited"
NUMOTHERSOCK="unlimited"
DCACHESIZE="unlimited"
NUMFILE="unlimited"
NUMIPTENT="unlimited"

# Disk quota parameters (in form of softlimit:hardlimit)
DISKSPACE="%(diskspace_soft)sG:%(diskspace_hard)sG"
DISKINODES="%(diskinodes_soft)s:%(diskinodes_hard)s"
QUOTATIME="%(quotatime)s"

# CPU fair scheduler parameter
CPUUNITS="%(cpuunits)s"
CPULIMIT="%(cpulimit)s"
CPUS="%(cpus)s"
"""
