openvz_template = """\
#+--------------------------------------------------------------+
#| CT configuration generated by OpenNode-tui openvz script \t|
#+--------------------------------------------------------------+
#| Input parameters were \t\t\t\t\t\t|
#+--------------------------------------------------------------+
#| MEMORY    : %(physpages_limit)sG \t\t\t\t\t\t|
#| SWAPPAGES : %(swappages_limit)sG \t\t\t\t\t\t|
#| DISK      : %(diskspace_soft)sG \t\t\t\t\t\t|
#| CPUS      : %(cpus)s \t\t\t\t\t\t|
#| CPULIMIT  : %(cpulimit)s%% \t\t\t\t\t\t|
#+--------------------------------------------------------------+
#| Generated : %(time)s \t\t\t|
#+--------------------------------------------------------------+


# VSwap limits
PHYSPAGES="0:%(physpages_limit)sG"
SWAPPAGES="0:%(swappages_limit)sG"

# Disk quota parameters (in form of softlimit:hardlimit)
DISKSPACE="%(diskspace_soft)sG:%(diskspace_hard)sG"
DISKINODES="%(diskinodes_soft)s:%(diskinodes_hard)s"
QUOTATIME="%(quotatime)s"

# CPU fair scheduler parameter
CPUUNITS="%(cpuunits)s"
CPULIMIT="%(cpulimit)s"
CPUS="%(cpus)s"
"""
